on: [push, pull_request]

name: Build from SVN

jobs:

  windows:
    name: Windows
    runs-on: windows-latest
    env:
      R_CRAN_WEB: "https://cran.rstudio.com"
      CRAN_RSYNC: 'mirrors.nic.cz::CRAN'
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ ucrt64 ]
    steps:

    - name: Prepare git
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: System dependencies
      shell: powershell
      run: |
        Import-Module .\.github\workflows\scripts.ps1
        SetTimezone
        InstallRtoolsExe
        InstallMiktex -ErrorAction SilentlyContinue;

    - name: "Fix rsync-recommended"
      shell: bash
      run: sed -i.bak 's/rsync -rc/rsync -r/' tools/rsync-recommended

    - name: Build and Check
      env:
        toolchain: ${{matrix.toolchain}}
      run: C:\rtools40\usr\bin\bash --login -c "$(cygpath ${env:GITHUB_WORKSPACE})/.github/workflows/rtools40-build.sh"

    - name: Setup tmate session
      if: failure()
      uses: mxschmitt/action-tmate@v3

    - name: Upload check results
      if: failure()
      uses: actions/upload-artifact@main
      with:
        name: tests
        path: tests
